// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXE9Q9VTPA1727OYqQpZ5dnFvOVXei60I',
    appId: '1:164196932037:web:e52049392d1f6adbca53ac',
    messagingSenderId: '164196932037',
    projectId: 'town-square-efb7b',
    authDomain: 'town-square-efb7b.firebaseapp.com',
    storageBucket: 'town-square-efb7b.firebasestorage.app',
    measurementId: 'G-GYSR4G0XGB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0xuvkDslgkO-lhJjL8JNLtWG3gn4NRU',
    appId: '1:164196932037:ios:daf9ae12b24ebb58ca53ac',
    messagingSenderId: '164196932037',
    projectId: 'town-square-efb7b',
    storageBucket: 'town-square-efb7b.firebasestorage.app',
    iosBundleId: 'com.example.townsquare',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxqLen-fImG_VzrnPiRqP69V9Uq0CLqpo',
    appId: '1:164196932037:android:7a7c87a4c28457f3ca53ac',
    messagingSenderId: '164196932037',
    projectId: 'town-square-efb7b',
    storageBucket: 'town-square-efb7b.firebasestorage.app',
  );
}
